'reproduction:required':
  comment: >
    This issue needs to be reproduced in order to continue.

    Please consult our guide on [minimal reproductions](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to understand what is needed.
'reproduction:provided':

    Issues requiring reproductions may be closed if no reproduction can be provided within two weeks.
  comment: >
    Thank you for providing a reproduction for this issue.

    The label will be updated to `reproduction:confirmed` once someone else has confirmed they can reproduce the problem with it.
