test:
  comment: >
    Test comment
'reproduction:required':
  comment: >
    This issue has been labeled as requiring a reproduction, usually because implementation won't be possible without it.

    Please consult our guide on [minimal reproductions](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to understand what is needed.
'reproduction:provided':
  comment: >
    Thank you for providing a reproduction.

    The label will be updated to `reproduction:confirmed` once someone else has confirmed they can reproduce the problem with it.
